import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { 
  ChevronLeft, 
  ChevronRight, 
  ArrowLeft, 
  ArrowRight, 
  Code2, 
  BookOpen, 
  Check, 
  Copy,
  Compass,
  ZoomIn,
  ZoomOut,
  Maximize2,
  Minimize2,
  RotateCcw,
  Contrast
} from 'lucide-react';
import { topics } from '../../entities/topic/model/topics';
import styles from './TopicDetailPage.module.css';

/**
 * TopicDetailPage Component.
 * Implements the core textbook content rendering, step-by-step visual proofs
 * generated by Asymptote, code viewer, and book pagination navigation.
 */
export const TopicDetailPage: React.FC = () => {
  const { topicId } = useParams<{ topicId: string }>();

  // Find current topic in the database
  const currentTopicIndex = topics.findIndex(t => t.id === topicId);
  const topic = topics[currentTopicIndex];

  // State for step-by-step graphic interaction
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [showCode, setShowCode] = useState(false);
  const [copied, setCopied] = useState(false);

  // Zoom & Pan states
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [isFullscreen, setIsFullscreen] = useState(false);

  // Image background configuration
  const [imageBg, setImageBg] = useState<'theme' | 'white' | 'dark'>(() => {
    const saved = localStorage.getItem('drawing-bg');
    return (saved === 'theme' || saved === 'white' || saved === 'dark') ? saved : 'theme';
  });

  useEffect(() => {
    localStorage.setItem('drawing-bg', imageBg);
  }, [imageBg]);

  // Reset steps, zoom & pan when transitioning to a different topic
  useEffect(() => {
    setCurrentStepIndex(0);
    setShowCode(false);
    setZoom(1);
    setPan({ x: 0, y: 0 });
    setIsFullscreen(false);
  }, [topicId]);

  // Reset zoom & pan when step changes
  useEffect(() => {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  }, [currentStepIndex]);

  const handleZoomIn = () => {
    setZoom(prev => Math.min(prev + 0.25, 4));
  };

  const handleZoomOut = () => {
    setZoom(prev => {
      const next = Math.max(prev - 0.25, 1);
      if (next === 1) {
        setPan({ x: 0, y: 0 });
      }
      return next;
    });
  };

  const handleResetZoom = () => {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  };

  const handleMouseDown = (e: React.MouseEvent) => {
    if (zoom === 1) return; // Only allow panning when zoomed in
    e.preventDefault();
    setIsDragging(true);
    setDragStart({ x: e.clientX - pan.x, y: e.clientY - pan.y });
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging) return;
    setPan({
      x: e.clientX - dragStart.x,
      y: e.clientY - dragStart.y
    });
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  // Handle case where topic is not found
  if (!topic) {
    return (
      <div className={styles.noStepsPlaceholder}>
        <Compass size={48} className={styles.icon} />
        <h2>Тему не знайдено</h2>
        <p>На жаль, за такою адресою немає геометричного матеріалу.</p>
        <Link to="/topic/pythagorean-theorem" className={styles.btnStep} style={{ marginTop: '1rem' }}>
          Повернутися до змісту
        </Link>
      </div>
    );
  }

  const hasSteps = topic.steps && topic.steps.length > 0;
  const currentStep = hasSteps && topic.steps ? topic.steps[currentStepIndex] : null;

  // Resolve book pagination links
  const prevTopic = currentTopicIndex > 0 ? topics[currentTopicIndex - 1] : null;
  const nextTopic = currentTopicIndex < topics.length - 1 ? topics[currentTopicIndex + 1] : null;

  // Handle copying Asymptote code to clipboard
  const handleCopyCode = () => {
    if (currentStep?.asyCode) {
      navigator.clipboard.writeText(currentStep.asyCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className={styles.detailContainer}>
      {/* Header section with breadcrumbs and title */}
      <section className={styles.headerSection}>
        <div className={styles.chapterBreadcrumb}>{topic.chapter}</div>
        <h1>{topic.title}</h1>

        {hasSteps && currentStep && (
          <div className={styles.mobileBgControls}>
            <span className={styles.bgLabel}>Фон:</span>
            <button 
              className={`${styles.mobileBgBtn} ${imageBg === 'theme' ? styles.activeBgBtn : ''}`} 
              onClick={() => setImageBg('theme')}
              title="Колір теми"
            >
              <Contrast size={14} />
              <span>Тема</span>
            </button>
            <button 
              className={`${styles.mobileBgBtn} ${imageBg === 'white' ? styles.activeBgBtn : ''}`} 
              onClick={() => setImageBg('white')}
              title="Білий"
            >
              <div className={`${styles.circlePreview} ${styles.circleWhite}`} />
              <span>Білий</span>
            </button>
            <button 
              className={`${styles.mobileBgBtn} ${imageBg === 'dark' ? styles.activeBgBtn : ''}`} 
              onClick={() => setImageBg('dark')}
              title="Темний"
            >
              <div className={`${styles.circlePreview} ${styles.circleDark}`} />
              <span>Темний</span>
            </button>
          </div>
        )}
      </section>

      {/* Main topic layout: Theory on left, Interactive visuals on right */}
      <div className={styles.topicLayout}>
        {/* Theory section */}
        <section className={styles.theorySection}>
          <h2 style={{ fontSize: '1.4rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <BookOpen size={20} style={{ color: 'var(--primary)' }} />
            Теоретичні відомості
          </h2>
          {topic.theory.map((paragraph, index) => (
            <p key={index}>{paragraph}</p>
          ))}
        </section>

        {/* Visual proof and Asymptote code section */}
        <section className={styles.visualSection}>
          <h2 style={{ fontSize: '1.4rem' }}>Візуальне доведення</h2>

          {hasSteps && currentStep ? (
            <>
              {/* Graphic SVG Viewer */}
              <div 
                className={`${styles.imageWrapper} ${
                  imageBg === 'white' ? styles.bgWhite : 
                  imageBg === 'dark' ? styles.bgDark : 
                  styles.bgTheme
                } ${isFullscreen ? styles.fullscreenWrapper : ''}`}
                onMouseDown={handleMouseDown}
                onMouseMove={handleMouseMove}
                onMouseUp={handleMouseUp}
                onMouseLeave={handleMouseUp}
                style={{ 
                  cursor: zoom > 1 ? (isDragging ? 'grabbing' : 'grab') : 'default',
                  overflow: 'hidden',
                  position: 'relative'
                }}
              >
                <img 
                  src={currentStep.svgPath} 
                  alt={currentStep.title} 
                  className={styles.graphicSvg} 
                  style={{
                    transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
                    transition: isDragging ? 'none' : 'transform 0.15s ease-out',
                    transformOrigin: 'center center'
                  }}
                  draggable={false}
                />

                {/* Floating background configuration controls */}
                <div 
                  className={styles.bgControls} 
                  onMouseDown={(e) => e.stopPropagation()}
                >
                  <button 
                    className={imageBg === 'theme' ? styles.activeBgBtn : ''} 
                    onClick={() => setImageBg('theme')}
                    title="Колір теми"
                  >
                    <Contrast size={14} />
                  </button>
                  <button 
                    className={imageBg === 'white' ? styles.activeBgBtn : ''} 
                    onClick={() => setImageBg('white')}
                    title="Білий"
                  >
                    <div className={`${styles.circlePreview} ${styles.circleWhite}`} />
                  </button>
                  <button 
                    className={imageBg === 'dark' ? styles.activeBgBtn : ''} 
                    onClick={() => setImageBg('dark')}
                    title="Темний"
                  >
                    <div className={`${styles.circlePreview} ${styles.circleDark}`} />
                  </button>
                </div>

                {/* Floating controls in the corner */}
                <div className={styles.zoomControls}>
                  <button onClick={handleZoomOut} disabled={zoom <= 1} title="Зменшити">
                    <ZoomOut size={16} />
                  </button>
                  <span className={styles.zoomLevel}>{Math.round(zoom * 100)}%</span>
                  <button onClick={handleZoomIn} disabled={zoom >= 4} title="Збільшити">
                    <ZoomIn size={16} />
                  </button>
                  <button onClick={handleResetZoom} disabled={zoom === 1 && pan.x === 0 && pan.y === 0} title="Скинути">
                    <RotateCcw size={16} />
                  </button>
                  <button onClick={() => setIsFullscreen(!isFullscreen)} title={isFullscreen ? "Згорнути" : "На весь екран"}>
                    {isFullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
                  </button>
                </div>
              </div>

              {/* Step info */}
              <div className={styles.codeContainer}>
                <h3 className={styles.stepTitle}>{currentStep.title}</h3>
                <p className={styles.stepDescription}>{currentStep.description}</p>
              </div>

              {/* Step Navigation Controls */}
              <div className={styles.controlsRow}>
                <button 
                  className={styles.btnStep}
                  onClick={() => setCurrentStepIndex(prev => Math.max(0, prev - 1))}
                  disabled={currentStepIndex === 0}
                  title="Попередній крок"
                >
                  <ChevronLeft size={16} /> Назад
                </button>

                <div className={styles.stepIndicators}>
                  {topic.steps?.map((_, idx) => (
                    <button
                      key={idx}
                      className={`${styles.dot} ${idx === currentStepIndex ? styles.activeDot : ''}`}
                      onClick={() => setCurrentStepIndex(idx)}
                      title={`Перейти до кроку ${idx + 1}`}
                    />
                  ))}
                </div>

                <button 
                  className={styles.btnStep}
                  onClick={() => setCurrentStepIndex(prev => Math.min((topic.steps?.length || 1) - 1, prev + 1))}
                  disabled={currentStepIndex === (topic.steps?.length || 1) - 1}
                  title="Наступний крок"
                >
                  Далі <ChevronRight size={16} />
                </button>
              </div>

              {/* Asymptote Code Drawer */}
              {currentStep.asyCode && (
                <div>
                  <button 
                    className={styles.codeToggle}
                    onClick={() => setShowCode(!showCode)}
                  >
                    <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                      <Code2 size={16} />
                      {showCode ? 'Сховати вихідний код Asymptote' : 'Показати вихідний код Asymptote'}
                    </span>
                    <span>{showCode ? '▼' : '▶'}</span>
                  </button>

                  {showCode && (
                    <div style={{ marginTop: '0.75rem' }} className={styles.codeContainer}>
                      <div className={styles.codeBlockHeader}>
                        <span>shared/assets/asymptote/{topic.id}_step{currentStepIndex + 1}.asy</span>
                        <button className={styles.btnCopy} onClick={handleCopyCode}>
                          {copied ? (
                            <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', color: 'var(--accent)' }}>
                              <Check size={14} /> Скопійовано!
                            </span>
                          ) : (
                            <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                              <Copy size={14} /> Копіювати
                            </span>
                          )}
                        </button>
                      </div>
                      <pre className={styles.codeBlock}>{currentStep.asyCode}</pre>
                    </div>
                  )}
                </div>
              )}
            </>
          ) : (
            <div className={styles.noStepsPlaceholder}>
              <Compass size={40} style={{ color: 'var(--text-muted)', marginBottom: '0.75rem' }} />
              <h3 style={{ fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '0.25rem' }}>
                Графіка знаходиться в розробці
              </h3>
              <p className={styles.stepDescription}>
                Для цієї теми векторні малюнки Asymptote ще не додані. Слідуйте крокам на сторінці «Про проект», щоб додати графіку!
              </p>
            </div>
          )}
        </section>
      </div>

      {/* Book-like Pagination (Prev/Next Chapter Topics) */}
      <section className={styles.bookPagination}>
        {prevTopic ? (
          <div className={styles.btnBookNav}>
            <span className={styles.navDirection}>Попередня тема</span>
            <Link to={`/topic/${prevTopic.id}`} className={styles.navTitle}>
              <ArrowLeft size={16} />
              <span>{prevTopic.title}</span>
            </Link>
          </div>
        ) : (
          <div></div> // Spacer
        )}

        {nextTopic ? (
          <div className={`${styles.btnBookNav} ${styles.rightAlign}`}>
            <span className={styles.navDirection}>Наступна тема</span>
            <Link to={`/topic/${nextTopic.id}`} className={styles.navTitle}>
              <span>{nextTopic.title}</span>
              <ArrowRight size={16} />
            </Link>
          </div>
        ) : (
          <div></div> // Spacer
        )}
      </section>
    </div>
  );
};
